# Generated by Django 5.2.4 on 2025-08-08 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ondc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheme_id", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("category_ids", models.JSONField()),
                (
                    "parent_item_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fulfillment_ids", models.JSONField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, null=True)),
                (
                    "isin",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "full_on_search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes",
                        to="ondc.fullonsearch",
                    ),
                ),
            ],
        ),
    ]
