# Generated by Django 5.2.4 on 2025-08-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ondc", "0002_scheme"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
