# Generated by Django 5.2.4 on 2025-08-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ondc", "0003_scheme_payload"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheme",
            name="item_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="matching_fulfillment",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheme",
            name="provider_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="MutualFundProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_id", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("bpp_id", models.CharField(db_index=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "mutual_fund_providers",
                "indexes": [
                    models.Index(
                        fields=["bpp_id", "is_active"],
                        name="mutual_fund_bpp_id_fb3256_idx",
                    )
                ],
                "unique_together": {("provider_id", "bpp_id")},
            },
        ),
        migrations.CreateModel(
            name="ONDCTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("message_id", models.CharField(max_length=100)),
                ("bap_id", models.CharField(max_length=200)),
                ("bap_uri", models.URLField()),
                ("bpp_id", models.CharField(max_length=200)),
                ("bpp_uri", models.URLField()),
                ("domain", models.CharField(default="ONDC:FIS14", max_length=50)),
                ("version", models.CharField(default="2.0.0", max_length=10)),
                ("action", models.CharField(max_length=50)),
                ("country_code", models.CharField(default="IND", max_length=3)),
                ("city_code", models.CharField(default="*", max_length=10)),
                ("timestamp", models.DateTimeField()),
                ("ttl", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ondc_transactions",
                "indexes": [
                    models.Index(
                        fields=["bpp_id", "transaction_id"],
                        name="ondc_transa_bpp_id_1247d9_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="ondc_transa_timesta_f2dd07_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BPPTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("static_terms_url", models.URLField(blank=True, null=True)),
                ("offline_contract", models.BooleanField(default=False)),
                ("additional_terms", models.JSONField(blank=True, default=dict)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bpp_terms",
                        to="ondc.ondctransaction",
                    ),
                ),
            ],
            options={
                "db_table": "bpp_terms",
            },
        ),
        migrations.CreateModel(
            name="SchemeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=100)),
                ("level", models.IntegerField(default=0)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ondc.schemecategory",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="ondc.mutualfundprovider",
                    ),
                ),
            ],
            options={
                "db_table": "scheme_categories",
                "unique_together": {("category_id", "provider")},
            },
        ),
        migrations.CreateModel(
            name="MutualFundScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheme_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=300)),
                ("code", models.CharField(default="SCHEME", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("lockin_period_days", models.IntegerField(blank=True, null=True)),
                ("nfo_start_date", models.DateField(blank=True, null=True)),
                ("nfo_end_date", models.DateField(blank=True, null=True)),
                ("nfo_allotment_date", models.DateField(blank=True, null=True)),
                ("nfo_reopen_date", models.DateField(blank=True, null=True)),
                (
                    "entry_load",
                    models.CharField(default="no entry load", max_length=100),
                ),
                ("exit_load", models.CharField(blank=True, max_length=100, null=True)),
                ("offer_documents_url", models.URLField(blank=True, null=True)),
                ("is_matched", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes",
                        to="ondc.mutualfundprovider",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes",
                        to="ondc.ondctransaction",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="schemes", to="ondc.schemecategory"
                    ),
                ),
            ],
            options={
                "db_table": "mutual_fund_schemes",
            },
        ),
        migrations.CreateModel(
            name="SchemePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_id", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=300)),
                ("code", models.CharField(default="SCHEME_PLAN", max_length=50)),
                ("isin", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "rta_identifier",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "amfi_identifier",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("REGULAR", "Regular"), ("DIRECT", "Direct")],
                        max_length=20,
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("GROWTH", "Growth"),
                            ("IDCW", "IDCW"),
                            ("DIVIDEND", "Dividend"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "idcw_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PAYOUT", "Payout"),
                            ("REINVESTMENT", "Reinvestment"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("consumer_tnc_url", models.URLField(blank=True, null=True)),
                ("is_matched", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="ondc.mutualfundscheme",
                    ),
                ),
            ],
            options={
                "db_table": "scheme_plans",
            },
        ),
        migrations.CreateModel(
            name="FulfillmentOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fulfillment_id", models.CharField(max_length=100)),
                (
                    "fulfillment_type",
                    models.CharField(
                        choices=[
                            ("LUMPSUM", "Lump Sum"),
                            ("SIP", "Systematic Investment Plan"),
                            ("STP", "Systematic Transfer Plan"),
                            ("SWP", "Systematic Withdrawal Plan"),
                            ("REDEMPTION", "Redemption"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "amount_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "amount_multiples",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "units_min",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "units_max",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "units_multiples",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("frequency", models.CharField(blank=True, max_length=10, null=True)),
                ("frequency_dates", models.TextField(blank=True, null=True)),
                ("instalments_count_min", models.IntegerField(blank=True, null=True)),
                ("instalments_count_max", models.IntegerField(blank=True, null=True)),
                (
                    "cumulative_amount_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillment_options",
                        to="ondc.schemeplan",
                    ),
                ),
            ],
            options={
                "db_table": "fulfillment_options",
            },
        ),
        migrations.AddIndex(
            model_name="mutualfundscheme",
            index=models.Index(
                fields=["provider", "status"], name="mutual_fund_provide_17b046_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mutualfundscheme",
            index=models.Index(
                fields=["nfo_start_date", "nfo_end_date"],
                name="mutual_fund_nfo_sta_82328c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mutualfundscheme",
            unique_together={("scheme_id", "provider")},
        ),
        migrations.AddIndex(
            model_name="schemeplan",
            index=models.Index(
                fields=["scheme", "plan_type", "option_type"],
                name="scheme_plan_scheme__36f12b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schemeplan",
            index=models.Index(fields=["isin"], name="scheme_plan_isin_0cbd51_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="schemeplan",
            unique_together={("plan_id", "scheme")},
        ),
        migrations.AddIndex(
            model_name="fulfillmentoption",
            index=models.Index(
                fields=["plan", "fulfillment_type"],
                name="fulfillment_plan_id_6a02d6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fulfillmentoption",
            unique_together={("fulfillment_id", "plan")},
        ),
    ]
